### ISSUE TITLE
Le Serveur GraphQL plante lors d'une Inscription lorsqu'il est lancé avec Docker

### ISSUE THREAD

**Issue by Minigugus** [Minigugus/CodinSchool#10]
Le Serveur s'arrête sans aucun message et la ligne suivante est retournée
> codinschool_web_1 exited with code 0

Pour reproduire : `docker-compose -f docker-compose.dev.yml up`

*PS : Je n'ai pas vérifié en mode production.*

**Comment by rigwild** [comment]
Pas moyen de retrouver une stack trace avec [docker logs](https://docs.docker.com/engine/reference/commandline/logs/) ?
