### ISSUE TITLE
Archived - Méthode d'activation de compte

### ISSUE THREAD

**Issue by rigwild** [Minigugus/CodinSchool#12]
## Description du problème
Lors de l'activation d'un compte, la mutation GraphQL attend 2 champs :

- Mail
- Code d'activation

Le mail est inutile, le code d'activation étant sécurisé, il peut être transmis seul.

### Proposition
Dans la base de données, le code d'activation est stocké en clair, ce qui est une faille de sécurité. Je propose de sauvegarder 2 champs :

- `activationId` : Contient un identifiant unique de clef d'activation
- `activationClefHash` : Contient la clef d'activation hashée

De cette manière, il faudrait envoyer l'id de la clef et la clef **non hashée** par email à l'utilisateur. Au moment de la vérification, la clef pourra être identifiée dans la base de données grâce à `activationId`, et la clef non hashée de l'utilisateur comparée à la clef hashée stockée.

### Résultat
En cas de piratage de la base de données, les clefs d'activation ne pourront pas être utilisées.
Cette proposition est également valide pour les clefs de réinitialisation de mot de passe futures.

**Comment by rigwild** [comment]
Je viens d'y penser : Avoir un champs `activationId` est inutile, il suffit de passer l'id du compte utilisateur.

**Comment by rigwild** [comment]
Correction du problème du champs `mail` en trop.
Je laisse ouvert pour l'amélioration possible du système.

**Comment by Minigugus** [comment]
Il semblerait que le même problème à lieu avec la *Réinitialisation de Mot de Passe* : **le code de réinitialisation est envoyé en clair**. De plus, l'adresse email de l'utilisateur est passé via l'URL envoyé dans le mail de réinitialisation. Il est donc envisageable d'appliquer cette mesure, ou tout du moins sur la *Réinitialisation de Mot de Passe*.
