### ISSUE TITLE
Champs "id" dans le schema GraphQL

### ISSUE THREAD

**Issue by rigwild** [Minigugus/CodinSchool#20]
## Description du problème
Les modifications faites côté front-end sont mise en cache afin de maximiser les performance en minimisant les appels au serveur.
Le problème est que Apollo map son cache sur le champs `id` des tables, ce qui fait que lors d'une modification de ce champs `id`, le cache est bugué.

## Problème
Si l'on édite l'identifiant d'un niveau, qu'on navigue dans les pages pour éditer ses exercices, un message d'erreur apparaît indiquant que le niveau n'a pas été trouvé. Cela est valable également pour la modification d'exercices.

#### 1. Empêcher la modification de tout champs `id`.
On ne permet au rédacteur de le créer uniquement lors de la création.
➕  Avantage : Rapide à faire, il suffit de griser les champs `id` et empêcher leur modification
➖  Désavantage : Si l'on change le titre, l'identifiant (visible dans la barre d'adresse) n'aura plus rien à voir avec le titre.

#### 2. Ajouter un champs `id` aléatoire et invisible
Rendre le champs `id` aléatoire, invisible et non modifiable. Ajouter un champs `id_url` modifiable, et correspondant à ce qui est visible dans la barre d'adresse et le fil d’Ariane.
➕  Avantage : plus aucun problème de cache, le champs `id` n'étant jamais modifié.
➖  Désavantage : Modifier pas mal de code.

**Comment by Minigugus** [comment]
Effectivement, cela pose problème...

En ce qui me concerne, je penche plutôt pour la **proposition n°1**, d'ici à ce que l'on trouve une solution.

La **proposition n°2** ne me semble pas une bonne idée, puisque cela reviendrait à *cacher* le problème plutôt que de le résoudre.

**Comment by rigwild** [comment]
Ok, je mets en place la proposition n°1. Je laisserai l'issue ouverte pour future référence.

**Comment by rigwild** [comment]
Problème résolu.
Je laisse ouvert pour future référence, le changement de l'url me semblant pas mal contraignant.
Commit : bde7f8d70222430fe4b77adaf83f525c1d10bab5
