### ISSUE TITLE
Archived - Champs "Code de départ" dans un exercice

### ISSUE THREAD

**Issue by rigwild** [Minigugus/CodinSchool#29]
## Proposition
La partie exercice n'est pas terminée. Cependant, je pense qu'il pourrait être intéressant de rajouter un champs `codeDeDepart` donnant la possibilité au rédacteur d'exercice de donner un morceau de code tout prêt.

## Problème
 - Comment gérer si plusieurs langages sont autorisés pour un même exercice ?
 - Un code par défaut pour chaque langage doit donc être prévu si le rédacteur ne souhaite pas en fournir ?

## Solution proposée
Ajouter un champs `codeDeDepart` de type JSON en base de données, retournant un objet du type suivant :
```json
{
  "JavaScript": "console.log('Hello world')",
  "PHP": "<?php echo 'Hello world'; ?>"
}
```
Concernant les codes par défaut des langages, nous pouvons les stocker en dur côté client pour ne pas surcharger la base de données de données fixes.

**Comment by Minigugus** [comment]
Cela me semble une bonne idée. En attendant l'ajout de cette fonctionnalité, tu peux effectivement stocker les codes de base côté client.

Exemple en C :
```c
#include <stdio.h>

int main()
{
  // Votre code ici.
  return 0;
}
```
