### ISSUE TITLE
Identification des messages/erreurs

### ISSUE THREAD

**Issue by rigwild** [Minigugus/CodinSchool#3]
Il serait utile de créer un module contenant la liste de tous les messages/erreurs de l'application. Cela faciliterait le traitement côté client, et serait très évolutif en cas de traduction de ces messages.

**Comment by Minigugus** [comment]
Il se trouve que depuis le commit 0e699cc0ebb6013248223f19195252c5506669f1, il est désormais possible de récupérer le code d'une erreur :

```json5
{
  "errors": [
    {
      "message": "L'adresse dev@codinschool.fr est déjà utilisée. Merci d'en choisir une autre.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "inscription"
      ],
      "extensions": {
        "code": "EMAIL_DEJA_UTILISE", // AJOUT
        "exception": {
          "props": {
            "email": "dev@codinschool.fr" // Supporte aussi le passage de propriétés ici
          }
        }
      }
    }
  ],
  "data": null
}
```
mais aussi de personnaliser l'objet `errors` côté serveur (cf. `apollo-server/erreurs.js`) :
```javascript
// La fonction ci-dessous est appelée lorsqu'une erreur est levée lors du traitement d'une requête GraphQL.
// `erreur` est ici l'objet `errors` qui sera retourné au client en JSON (cf. ci-dessus).
// Actuellement, elle est définie ainsi :
export default erreur => erreur
```

Si vous avez des suggestions d'amélioration de l'erreur retournée, n'hésitez pas à les partager :smiley:

**Comment by rigwild** [comment]
Ton implémentation concerne les erreurs serveur. Cependant, j'évoquais le fait d'intégrer un système comprenant **tous** les textes de l'application.
Je pense que cela suffira pour le moment, je clos l'issue.
Elle sera de nouveau ouverte si une telle fonctionnalité plus complète est attendue. 👍
