### ISSUE TITLE
Problème énumérations GraphQL

### ISSUE THREAD

**Issue by rigwild** [Minigugus/CodinSchool#31]
## Problème
L'énumération des permissions de rôles dans GraphQL se fait à l'aide de l'introspection.
Cela a été mis en place afin de segmenter chaque permissions dans son propre module du serveur.

Cependant, en production, cela est désactivé par défaut, rendant impossible au serveur de trouver l'ensemble des permissions, faisant planter les requêtes de permission.

## Question
Activer l'introspection dans GraphQL en mode production est-il une bonne pratique ? Cela est-il un problème de performance et/ou de sécurité ?

## Solutions potentielles
 - Activer l'introspection dans le serveur GraphQL (Comment faire ? Où se trouve sa configuration ?)
 - Faire un module du serveur GraphQL listant les permissions possibles (Moins de segmentation)

## Solution temporaire choisie
Appliquer la liste des permissions en dur côté front-end. Cela n'est pas cohérent, car cela sous-entend que lorsque le serveur sera modifié, il faudra modifier le client.
Voir : https://github.com/Minigugus/CodinSchool/commit/f1d50f7bdef76dff93cefefd8aec39267dcea29b

## Plus d'informations
 - https://graphql.org/learn/introspection/

**Comment by rigwild** [comment]
@Minigugus Merci de répondre à cette partie.

> ## Question
> Activer l'introspection dans GraphQL en mode production est-il une bonne pratique ? Cela est-il un problème de performance et/ou de sécurité ?

**Comment by Minigugus** [comment]
D'après [GraphGL Mastery](https://graphqlmastery.com/blog/graphql-security-in-node-js-project) (traduit par [DeepL](https://www.deepl.com/translator))
> Si vous êtes familier avec les outils comme GraphiQL, vous vous demandez peut-être, comment vous pouvez tout savoir sur le schéma. Dans GraphQL il y a une option pour exécuter les requêtes dites d'introspection du schéma. Vous pouvez utiliser cet outil pour tout savoir sur le système de type du schéma, y compris ce que vous pouvez rechercher, les mutations disponibles, etc. Si vous êtes dans un environnement de développement, il est certainement utile de permettre l'introspection à diverses fins. En production, cependant, il peut divulguer des informations importantes pour les attaquants potentiels ou il ne fera que révéler des informations sur votre nouvelle fonctionnalité, qui n'est pas mise en œuvre sur l'interface. Si vous voulez résoudre ce problème, vous pouvez utiliser la bibliothèque GraphQL GraphQL Disable Introspection. Elle vous permet d'ajouter des règles de validation qui désactivent l'introspection. Désactiver l'introspection pour tout le monde est parfois un peu limité. ***Il est donc préférable d'ajouter l'introspection à la demande ou de n'autoriser l'introspection que pour certaines portées.***

Mon commit précédent 609f651 se contente de permettre l'activation de l'introspection via la variable d'environnement `GRAPHQL_INTROSPECTION`. Cependant, comme détaillé dans la phrase en gras du paragraphe précédent, il pourrait être intéressant, en production, de filtrer les requêtes pour n'autoriser que le type `Permission` à être *introspecté*. Par contre, cela devra être fait *à la main*, dans le sens où `ApolloServer` ne prend pas en charge ce système de filtrage.
