### ISSUE TITLE
Archived - Génération des identifiants de niveaux et/ou exercices

### ISSUE THREAD

**Issue by Minigugus** [Minigugus/CodinSchool#38]
## Proposition
Utiliser le titre, transformé en kebab-case ?
`Le Titre de mon Niveau` donnerais par exemple `le-titre-de-mon-niveau`

**Comment by rigwild** [comment]
J'ajoute le tag `Back-End` car cela peut être traité aussi de ce côté.

**Comment by rigwild** [comment]
Proposition d'implémentation uniquement côté serveur :
```js
/**
 * Convertir une chaîne en kebab case sans accent.
 * 
 * @param {string} str la chaîne à convertir
 * @returns {string} la chaîne en kebab case
 */
const toKebabCase = str => str.normalize('NFD').replace(/[\u0300-\u036f]/g, "").replace(/\s+/g, '-')
```

**Comment by rigwild** [comment]
(Mauvaise manip' pour la fermeture !)

**Comment by Minigugus** [comment]
J'avais initialement omis le label `Back-End` puisque actuellement, l'identifiant est choisis côté *Front*, et nécessiterais ainsi moins de modifications côté *Front* que *Back* et éviterais en plus de restreindre l'utilisateur en lui imposant un identifiant, notamment s'il est déjà utilisé.

Ma première proposition aurait été de compléter automatiquement le champs `id` lors de la saisie du titre du Niveau/Exercice si ce champ n'a pas encore été modifié manuellement. Cela permettant ainsi à l'utilisateur d'avoir un aperçu de l'identifiant du niveau, qui, à l'heure actuelle, n'est pas modifiable.

**Comment by rigwild** [comment]
On utilise une API, je te rappelle.. Ne pas le gérer côté serveur n'est pas une bonne chose (envoyer n'importe quoi par requête HTTP).

**Comment by Minigugus** [comment]
Je n'ai pas dit de ne pas le gérer côté serveur, simplement de le *générer* côté client. La taille des identifiants est déjà limitée (31 caractères pour les niveaux et exercices), il ne reste ensuite qu'à les valider côté serveur, voir à les convertir encore en fois. Ce que je voulais dire dans mon message est qu'il me parait plus avantageux de générer les identifiants devant l'utilisateur, afin qu'il en ait déjà un aperçu, plutôt que côté serveur où dans ce cas l'identifiant ne sera connu qu'une fois le Niveau/Exercice créé.

**Comment by rigwild** [comment]
Ok ça me va, j'ouvre une PR et te laisserai faire la partie serveur.
J'ajoute aussi la mise en minuscule.
```js
/**
 * Convertir une chaîne en kebab case sans accent.
 * 
 * @param {string} str la chaîne à convertir
 * @returns {string} la chaîne en kebab case
 */
const toKebabCase = str => str.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/\s+/g, '-').toLowerCase()
```

**Comment by rigwild** [comment]
Ajout du remplacement des symboles par 1 seul `-`.
```js
/**
 * Convertir une chaîne en kebab case sans accent ni symboles interdits.
 *
 * @param {string} str la chaîne à convertir
 * @returns {string} la chaîne en kebab case
 */
const toKebabCase = str => str
  .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  .replace(/[`~!@#$%^&*()_|+\-=?;:'",.<>\{\}\[\]\\\/]/gi, '-')
  .replace(/\s+|\-+/g, '-')
  .toLowerCase()
```

**Comment by rigwild** [comment]
Proposition validée.
